spring:
  application:
    name: sample-service
  main:
    banner-mode: "off"
  jmx:
    enabled: true
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
