spring:
  main:
    banner-mode: "off"
#    web-application-type: none
  jmx:
    enabled: true
#  application:
#    admin:
#      enabled: true
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
