@startuml
entity SigningKeyBlock <<Set>> {
  epochSecondsBlock: long
  --
  jwks: JSON Web Key Set
  <<ttl>> expiresOn: Instant
}
note left of SigningKeyBlock::jwks
This contains a public/private
keypair suitable for signature
generation
end note
entity Session <<Hash>> {
  jti : UUID
  --
  secretClaims : JSON
  issuedOn : Instant
  verificationJwk : JSON Web Key
  <<ttl>> expiresOn: Instant
}
note right of Session::verificationJwk
This contains the public key only
suitable for verification
end note

@enduml