name: Build
on:
  push:
    branches:
      - rework
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  expo-app:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: yarn install --frozen-lockfile
      - run: yarn workspace run test --coverage --ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=trajano
            -Dsonar.projectKey=spring-docker-swarm-expo-app
