openapi: 3.1.0
info:
  title: Spring Cloud Docker Swarm
  version: 3.0.0
  description: |
    An implementation of Spring Cloud that utilizes Docker Swarm for service discovery and provides OAuth-like
    functionality for controlling access to the system.
    
    This is using the "SimpleIdentityProvider" which is used for demo and testing purposes.
  license:
    name: EPL-2.0
    url: https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt
servers:
  - description: local direct
    url: http://localhost:28082
    variables: {}
paths:
  /auth:
    $ref: "./simple-auth.yaml#/paths/~1auth"
  /refresh:
    $ref: "./auth.yaml#/paths/~1refresh"
  /whoami:
    $ref: "./whoami.yaml#/paths/~1whoami"
