openapi: 3.1.0
paths:
  /whoami:
    get:
      summary: Show request headers
      operationId: whoami
      responses:
        200:
          description: Request headers
          content:
            text/plain:
              example: |
                Hostname: 13cecf3dbf5d
                IP: 127.0.0.1
                IP: 10.0.1.5
                IP: 172.18.0.8
                RemoteAddr: 10.0.1.69:36176
                GET /whoami HTTP/1.1
                Host: 10.0.1.5
                User-Agent: PostmanRuntime/7.29.0
                Accept: */*
                Accept-Encoding: gzip, deflate, br
                Authorization: Bearer eNoVjjcOo0AAAF_EiWigJBnvYliSSQ0imgVMNCa8_u6KaUYaaaoTLlnoYIRhZ4XOHl-wRR5JW23BPH1nT_ziG_sOaXrUx_TfrEUn2FJhZ_oOfiqwyfXif-u9rtdhYij-qU44l3r3X-LigvhFaXR8UnIZWiDuKA2FEy5C6AK844IJMGhHnNDiL1HACj4BWyjgZvox9Y_dvABlReQfow65gQstCoqpEACFuFCZ9W2XthmU2jOvJX9O9TgUOgU_n9Jtz_fO2V41yA5f38hO8ZJGtc35S9a6_VHZdk9Gf5BOfYspKSeOnvlK_CiPaWxn3i8lSyF4lf39Eb25Ijdewe3h0uFUHqbn5WuyMgFhVfSstHfZYbQyOvHcHEeyKo8GJ2fBkfxoLBXDiG3bJF-z6Hx0RPpbaodbuNLaw-7XLLDdpd4exIGzsi_uy0SpkoN4xGHrvhkMBXVfIGh58g8vSE1VI5PceIOAvLPTDiakDqTzTJ4aINJoKHuP8YE-aF2IpX8rsmPJk7KfYBDnJiY_x8jJoG5UQRhqh_kYmOSuQ_s2wyyrE2h7ZlQU1tNO_JR83c18WXGELG0yjY3chJ1UFRi2SdFpqp-Y1khyW8s0dF17uH-bsahF-BNz8AsZShQYQlGDWBN6YuLqabMhf2wpMuiNvXd8Jj5KZFy3H5ss7FXkC53RpNE07M5NiIRRyvW3qpr3YMSVL0jzhvkE2aPkBJBObX8Lx-p96Qs-PP7tos88iUH_pW8vYgHfn0oucyQe-w-9OtLMoMUgzWVduCpBw2OKbeaVZ5nP_c4UHf6oRDzm-0cVbzvT7DFVd0jJguVc1r3-drIYLBtnLgZ6W_GPX8odVWvkCHGpcyrmUDTSRXZVtvD8d3Kaai10qdJzDgvjv7RmHC8
                Forwarded: proto=http;host="localhost:28082";for="10.0.0.2:49716"
                Postman-Token: 209c6cc6-25ed-4a0e-afcb-324db834d557
                X-B3-Parentspanid: 71bb8c5d452ebbe6
                X-B3-Sampled: 1
                X-B3-Spanid: e77b9553fe3f25d8
                X-B3-Traceid: 627176c2b252abed7feb13dcfeca43e0
                X-Forwarded-For: 10.0.0.2
                X-Forwarded-Host: localhost:28082
                X-Forwarded-Port: 28082
                X-Forwarded-Proto: http
                X-Jwt-Assertion: eyJhbGciOiJub25lIn0.eyJqdGkiOiJiczJiU1E2Yy1BdWNIYk1EOWpicWJRIiwic3ViIjoiZ29vZCIsImV4cCI6MTY1MTYwMzI1NX0.
                X-Jwt-Audience: 
        401:
          $ref: "./components.yaml#/components/responses/invalid-token"

