openapi: 3.1.0
paths:
  /whoami:
    get:
      summary: Show request headers
      description: |
        A sample service endpoint that shows the headers and OS information in JSON format using
        [`containous/whoami`](https://hub.docker.com/r/containous/whoami) image.
      operationId: whoami
      responses:
        200:
          description: Request headers
          content:
            application/json:
              example: {
                "hostname": "c1fb226d2e1f",
                "ip": [
                  "127.0.0.1",
                  "10.0.7.246",
                  "172.18.0.6"
                ],
                "headers": {
                  "Accept": [
                    "*/*"
                  ],
                  "Accept-Encoding": [
                    "gzip, deflate, br"
                  ],
                  "Authorization": [
                    "Bearer eNotkNuya0AQhp_ILsZhyWWYkBEzgjC4SUlIDEKC5fT0W3bt6uqbrvr-Q-eL1aXUZQ5Dk0NdGVOPOT4v4kss2Rd3xvA5OFAriM9LDiRVfAlkAmMBU8Rs3Spu5n1jLT9YkUCYtfuTL9aaULIkkTtkUfhOdKSg0uUTk9QOPACb4sUxg4HACjg6L2NYFDZ1QQKNEq8Vn8Ciwj7qUUOEmG3sKxtvwP1nFgNS30U8ZOauS6g0JFExpZFV3xfhfWPCkFJZyMxwRWU72eUBkDL-rrixS0KTLRNp7cgbUxD-2jSU7ma93fDGScON1r9Z5G1aSMG6tOL_Q_SJfX02zZmUweLA_UTWw7xpfjKz-pav0yD5pboAPD5riVi0_jH0KNTqoCxExCaWRuSbiaVHj7_DdrTBPMbA6FNzt2b69jRoO4GtBKLmdRlwk33p46fsSSTK_ThzKXe6Nrhrg61crKa-fGvKaG6uc6yZdmL1nVt-agJK70bfAc3hEh5PtFlHdL9Ipy4EA8efQc0b09kxFv964eNe4M78-Rh_Ai2w4umnrUhurGqIqZmzd1cmMwp340WNbTlspb7P-tnhGChUmV9ej6hwzxPSWmMOT7YqvGTU5i-Nu17zQvEMpRai1u51MErc03p_-P4uXRMQ-f4qAm41e3KcoKcw6Bera6uetz9USBcFZTmXU6ehPOB6frgdBajK5F2Dw5CW78LFDTN4FjPYUNBkwxxyXHZVX-teOT2oToef_PmqTSo3VTg-9-nyCPZ_AXM-9b4"
                  ],
                  "Content-Length": [
                    "0"
                  ],
                  "Forwarded": [
                    "proto=http;host=\"localhost:28082\";for=\"10.0.0.2:35598\""
                  ],
                  "Postman-Token": [
                    "96242d85-73d6-467a-82f8-9cc9cfbe48bb"
                  ],
                  "User-Agent": [
                    "PostmanRuntime/7.29.0"
                  ],
                  "X-B3-Parentspanid": [
                    "c480d65563564867"
                  ],
                  "X-B3-Sampled": [
                    "1"
                  ],
                  "X-B3-Spanid": [
                    "810afed869e87a87"
                  ],
                  "X-B3-Traceid": [
                    "6283bc5f90b235ca4f2ec3d94aa7448e"
                  ],
                  "X-Forwarded-For": [
                    "10.0.0.2"
                  ],
                  "X-Forwarded-Host": [
                    "localhost:28082"
                  ],
                  "X-Forwarded-Port": [
                    "28082"
                  ],
                  "X-Forwarded-Prefix": [
                    "/whoami"
                  ],
                  "X-Forwarded-Proto": [
                    "http"
                  ],
                  "X-Jwt-Assertion": [
                    "eyJhbGciOiJub25lIn0.eyJzZWNyZXQtdXVpZCI6IjQ0ZGNlODE2LWMyOGUtNDk2OC05MDhhLWQ2ZDFjMzk0ZDhkMSIsInN1YiI6Imdvb2QiLCJhY2Nlc3MtdG9rZW4tZXhwaXJlcy1pbi1taW51dGVzIjowLjE2NjY2NjY3LCJyZWZyZXNoLXRva2VuLWV4cGlyZXMtaW4tbWludXRlcyI6MC4zMzMzMzMzNCwiZXhwIjoxNjUyODAwNzExLCJqdGkiOiJlaUZuWC12R0doN3hoSHVRWDBlUjh3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdCJ9."
                  ],
                  "X-Jwt-Audience": [
                    ""
                  ]
                },
                "url": "/api",
                "host": "10.0.7.246",
                "method": "GET"
              }
        401:
          $ref: "./components.yaml#/components/responses/invalid-token"

